# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2023-01-18 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mobileno',
            field=models.IntegerField(),
        ),
    ]
